### ISSUE TITLE
Понятнее об уведомлениях

### ISSUE THREAD

**Issue by cDonut** [Raiffeisen-DGTL/ecom-API#2]
![image](https://user-images.githubusercontent.com/17448045/108204446-64f78000-7156-11eb-8e57-daccf057e085.png)

1. Не совсем понятно как составить строку (amount|sbpMerchantId|order|paymentStatus|transactionDate) - нужно ли в нее добавлять символы "|"
2. Похоже в адресе https://test.ecom.raiffeisen.ru<URL обработчика уведомлений на стороне партнёра> должно быть только <URL обработчика уведомлений на стороне партнёра>
3. Было бы хорошо, если пример был с заголовком рассчитанной контрольной строки X-Api-Signature-SHA256, чтобы можно было сразу проверить корректность обработки колбэка на своем сервере.

**Comment by user-ecom-git** [comment]
Добрый день!
Прошу прощения, за столь долгий ответ.
1. Строка составляется с | 
2. Да , к сожалению упирались в инструмент , сейчас  описали уведомления как event и все отображается корректно
3. К сожалению , пример требует отображения секретного ключа ,  для проверки всегда можно сделать тестовый платеж , так же пример обработки заголовка можно посмотреть в Java SDK
